### PR TITLE
Adds Runtime Permission check android 6+ & Fixes missing AAPT option

### PR DESCRIPTION
**Pull request by NmdOfficial**
Fixed issue https://github.com/mit-cml/appinventor-sources/issues/1190

### CODE REVIEW

**Comment by NmdOfficial** [comment]
This line in form.java


checks after the app start, which permissions are added in the manifest file.

Then it checks if a permission was granted or not.
And then we see the default android permission dialog where the system ask's the user if he want to grant or denied a permission.

With this method we don't have to add new blocks to every component which needs a runtime permission check.

**Comment by ewpatton** [comment]
@NmdOfficial One concern I have with this permissions approach is that all of the permissions are requested up front when the app runs, even if it does not make sense for the workflow of the app. For example, if I build an app with a login screen that then moves to a page where I track location on a map, as a developer I might not want to prompt for location permissions until the user logs into their account. My plan was to make the request for permissions seamless when the app developer enables components such as the LocationSensor to maintain backward compatibility, but also add the blocks to allow for finer grain permission checking/requesting when it makes sense from an app logic perspective.

**Comment by NmdOfficial** [comment]
Okay. I understand what you mean.
What do you think what will be the best way to do it?
Add the permission check on echt method of a component? 
That will be a lot of work.

**Comment by p4ssw0rd** [comment]
I prefer to get all the permissions when the app starts.Do not add blocks or delay requests.This is easier for developers, ai developers are not professional developers after all.What do you think?

**Pull request closed without merging**
